version: '3.3'
services:
  db: 
    container_name: postgres_container
    image: postgres:16.0 # https://hub.docker.com/_/postgres/tags
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432" # External port is changed to prevent duplication with local Psql installation PORT
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      # before start create with commend: docker network create pg-network
      - pg-network
  pgadmin:
      container_name: pgadmin4_container
      image: dpage/pgadmin4:7.7
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: password
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "8080:80"
      volumes:
        - pgadmin-data:/var/lib/pgadmin
      networks:
        - pg-network
volumes:
  db-data:
    driver: local
  pgadmin-data:
    driver: local

networks:
  pg-network:
    driver: bridge
